// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  FundamentalsSidebar: [{ type: 'autogenerated', dirName: 'fundamentals' }],
  //BatterySidebar: [{ type: 'autogenerated', dirName: '02_battery' }],
  //AdvancedSidebar: [{ type: 'autogenerated', dirName: '03_advanced-concepts' }],
  //SystemAlgorithmSidebar: [{ type: 'autogenerated', dirName: '04_system_and_algorithms' }],
  //ModelingDesignSidebar: [{ type: 'autogenerated', dirName: '05_modeling_design' }],
  //TestingValidationSidebar: [{ type: 'autogenerated', dirName: '06_testing_and_validation' }],
  //GlossarySidebar: [{ type: 'autogenerated', dirName: '07_glossary' }],
  //ReferencesSidebar: [{ type: 'autogenerated', dirName: '08_references' }],
};

export default sidebars;

