// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  fundamentalsSidebar: [{ type: 'autogenerated', dirName: 'theory/01_fundamentals' }],
  agingDegradationSidebar: [{ type: 'autogenerated', dirName: 'theory/02_aging_degradation' }],
  chemistrySidebar: [{ type: 'autogenerated', dirName: 'theory/03_chemistry_design_principles' }],
  batteryPackSidebar: [{ type: 'autogenerated', dirName: 'theory/04_battery_pack' }],
  thermalManagementSidebar: [{ type: 'autogenerated', dirName: 'theory/05_thermal_management' }],
  characteristicsSidebar: [{ type: 'autogenerated', dirName: 'theory/06_battery_characteristics' }],
  sizingOptimizationSidebar: [{ type: 'autogenerated', dirName: 'theory/07_battery_sizing' }],
  batteryManagementSidebar: [{ type: 'autogenerated', dirName: 'theory/08_bms' }],
  bmsDesignArchitectureSidebar: [{ type: 'autogenerated', dirName: 'theory/09_bms_architecture' }],
  modelingTestingSidebar: [{ type: 'autogenerated', dirName: 'theory/10_modeling_testing' }],
  glossarySidebar: [{ type: 'autogenerated', dirName: 'glossary' }],
  referencesSidebar: [{ type: 'autogenerated', dirName: 'references' }],
};

export default sidebars;

